### ISSUE TITLE
Improvement: Use heater on HTU21D/Si7021

### ISSUE THREAD

**Issue by matthijskooijman** [meetjestad/mjs_firmware#13]
The temp/humidity sensor can sometimes get saturated on high humidity (or drift up on long periods of high humidity). To prevent this, a small heater can be enabled to prevent condensation.

On the HTU21D, the heater can just be enabled/disabled, on the Si7021 you can select different power levels.

**Comment by PeterDemmer** [comment]
I've implemented full heater control for the Si7021, see https://github.com/PeterDemmer/meetjestad/tree/master/mjs_Si7021_Library

**Comment by matthijskooijman** [comment]
Hm, seems this is a duplicate of #9, so I'm closing this one.
